config:
  fallback-icon: "?"
  show-name: true
  icon-position: "left"

icons:
  claude:      "" # nf-fa-robot
  pay:         "" # nf-fa-money_bill_wave
  nix:         "󱄅" # nf-dev-nix
  git-wrapper: "" # nf-dev-git
